name: first workflow
env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

on: 
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
    - name: firstJob script
      shell: cmd
      run: echo Hellow World! This is the firts job
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: greetings
      id: greetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ inputs.who-to-greet }}
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"    

  secondjob:
    runs-on: ubuntu-latest
    needs: firstjob
    env:
      JOB_VAR: " This is a job variable"
    steps:
      - name: secondJob script
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at the step level"
        shell: bash
        run: |
          echo this is the second job
          echo and this is a mulyi-line script
  
