name: first workflow

on: 
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    steps:
    - name: firstJob script
      shell: cmd
      run: echo Hellow World! This is the firts job
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: greetings
      id: greetings
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.greetings.outputs.time }}"    

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is the second job
          echo and this is a mulyi-line script
  
